version: "3"
services:
  spark:
    image: jupyter/pyspark-notebook
    container_name: spark-node
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/home/jovyan/
  cassandra:
    image: cassandra:latest
    container_name: cassandra-node
    ports: 
      - "9042:9042"
      - "9160:9160"